### ISSUE TITLE
What am I supposed to do with AuthenticationRequiredException, and other related questions

### ISSUE THREAD

**Issue by ChrisTitos** [andretietz/retroauth#84]
Hi,

I'm a bit confused about the new `AuthenticationRequiredException` you introduced in #68 . Why is this exception thrown? After this exception the request has failed, how do I know when to retry the request?

Also, when I make a call in `Activity.onCreate` the login activity doesn't open because the `ActivityManager.activity` is null, probably because of [this line](https://github.com/andretietz/retroauth/blob/master/retroauth-android/src/main/java/com/andretietz/retroauth/ActivityManager.kt#L60). Is there a reason you don't push the activity on `onActivityCreated`?

When the login activity _does_ open (when clicking a refresh button for example) and if I then cancel the login by going back, I don't seem to get a `AuthenticationCanceledException`, nothing seems to happen. Is this because the opening of the login activity is now separate from the actual authenticated call being made?

**Comment by andretietz** [comment]
Ok, here a bit background:

When the user is doing an authenticated request and he's logged out for whatever reason, then the request must be canceled. In earlier versions this was not the case. I [had to do this](https://github.com/andretietz/retroauth/issues/68) in order to avoid a deadlock which caused the app to send no request at all anymore.
