### ISSUE TITLE
Retrofit 2.5.0 crash

### ISSUE THREAD

**Issue by alashow** [andretietz/retroauth#85]
Hey,

If I change Retrofit version to `2.5.0` my app crashes with this stacktrace because of Retroauth:
```
java.lang.NoSuchMethodError: No virtual method defaultCallAdapterFactory(Ljava/util/concurrent/Executor;)Lretrofit2/CallAdapter$Factory; in class Lretrofit2/Platform; or its super classes (declaration of 'retrofit2.Platform' appears in /data/app/app.debug-od8qquOpDpUaSqITAUoBgw==/split_lib_dependencies_apk.apk:classes2.dex)
        at retrofit2.Retrofit2Platform.defaultCallAdapterFactory(Retrofit2Platform.kt:31)
        at com.andretietz.retroauth.Retroauth$Builder.build(Retroauth.kt:115)
```

Retroauth uses [`Platform#defaultCallAdapterFactory(executor)`](https://github.com/andretietz/retroauth/blob/80cfca4f83d0a311b0c3011650249173de1a93e0/retroauth/src/main/java/retrofit2/Retrofit2Platform.kt#L29) but in 2.5.0 it's renamed to `Platform#defaultCallAdapterFactories(executor)`.

**Comment by andretietz** [comment]
Ill do an update for retrofit and other libraries together in here:
https://github.com/andretietz/retroauth/pull/87

Thanks for the hint.

Just to point that out for others, this is not really a bug since you could use retrofit < 2.5.0 with which the library was build initially. For the 3.0.0 release I will try to update all libraries accordingly

**Comment by andretietz** [comment]
beta8 has been released where (not only) retrofit has been updated
