### ISSUE TITLE
[BUG] In AndroidOwnerManager.kt, getOwners should not return all accounts but only of the given type

### ISSUE THREAD

**Issue by amit-Newput** [andretietz/retroauth#95]
Hi

As per OwnerStorage.kt interface,
**

@param ownerType type of the owners you want to receive.
@return a list of [OWNER]s of the given type
*/
`
fun getOwners(ownerType: OWNER_TYPE): List`

while in AndroidOwnerManager.kt, it returns all accounts. This is causing issues when Android AccountManager has multiple accounts but of different account types.

https://github.com/andretietz/retroauth/blob/0c58ca87568544574462678b616523588b177df6/retroauth-android/src/main/java/com/andretietz/retroauth/AndroidOwnerStorage.kt#L79

I think it should return accounts of specific owner type.

**Comment by andretietz** [comment]
In most cases this is only YOUR account type, because I am [excluding the permission to get all accounts](https://github.com/andretietz/retroauth/blob/master/retroauth-android/src/main/AndroidManifest.xml#L4) (on api 22 and lower). This causes the system to only take the accounts which belong to this application.

But for lower api versions you're right, this should be covered.
