### ISSUE TITLE
[Question] about RetroauthCallAdapterFactory

### ISSUE THREAD

**Issue by oahmedazab** [andretietz/retroauth#97]
i had a question about RetroauthCallAdapterFactory specially about its first parameter
`private val callAdapterFactories: List<CallAdapter.Factory>`.

why we are passing the factories as parameter while we can get it from retrofit instance passed to `get` method. this way we don't have to do `Retrofit2Platform` workaround to get the `defaultCallAdapterFactories` 

i am just curious about this approach if you can tell me more about it that would be great, thanks

**Comment by andretietz** [comment]
This is a very good point. Retrofit iterates through the factories when a request is made(in order):

```
retrofit:
  - factory1
  - factory2
  - defaultFactories
```

using retroauth, retrofit will be setup like this (in order):

```
retrofit:
- RetroauthCallAdapterFactory
  - factory1
  - factory2
  - defaultFactories
- defaultFactories
```

This is to make sure, that we're definitely hitting our library before hitting any other one.

If we now would take all factories, setup in retrofit, we would include the RetroauthCallAdapterFactory, which then of course causes an infinite recursion, if we don't filter. Since this was a Java Library and filtering was a pain and to a lot of code, I decided agains this.

Since this is easier using kotlin, I will do this (if I don't face any other issues with it.).
Thank you very much for this hint.

**Comment by andretietz** [comment]
done and merged

**Comment by oahmedazab** [comment]
great, thank you for clarification
very good job
